// <auto-generated />
using System;
using DatabaseAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fias.Migrations
{
    [DbContext(typeof(FiasDatabaseContext))]
    partial class FiasDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DatabaseAPI.Models.AddressObject", b =>
                {
                    b.Property<Guid>("AOID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ACTSTATUS");

                    b.Property<string>("AOGUID");

                    b.Property<int?>("AOLEVEL");

                    b.Property<string>("AREACODE");

                    b.Property<string>("AUTOCODE");

                    b.Property<int?>("CENTSTATUS");

                    b.Property<string>("CITYCODE");

                    b.Property<string>("CODE");

                    b.Property<string>("CTARCODE");

                    b.Property<int?>("CURRSTATUS");

                    b.Property<DateTime?>("ENDDATE");

                    b.Property<string>("FORMALNAME");

                    b.Property<string>("IFNSFL");

                    b.Property<string>("IFNSUL");

                    b.Property<int?>("LIVESTATUS");

                    b.Property<string>("OFFNAME");

                    b.Property<string>("OKATO");

                    b.Property<string>("OKTMO");

                    b.Property<int?>("OPERSTATUS");

                    b.Property<string>("PARENTGUID");

                    b.Property<string>("PLACECODE");

                    b.Property<string>("PLAINCODE");

                    b.Property<string>("PLANCODE");

                    b.Property<string>("POSTALCODE");

                    b.Property<string>("REGIONCODE");

                    b.Property<string>("SHORTNAME");

                    b.Property<DateTime?>("STARTDATE");

                    b.Property<string>("STREETCODE");

                    b.Property<string>("TERRIFNSFL");

                    b.Property<string>("TERRIFNSUL");

                    b.Property<DateTime?>("UPDATEDATE");

                    b.HasKey("AOID");

                    b.ToTable("AddressObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
